<?php

return [
    'main'                  => 'Головна',
    'about'                 => 'Про сайт',
    'page404'               => 'Page404',
    'reg'                   => 'Реєстрація',
    'reg_res'               => 'Звіт про реєстрацію',
    'entry'                 => 'Вхід',
    'entry_res'             => 'Звіт про вхід',
    'exit'                  => 'Вихід',
    'nets'                  => 'Тег: сітки',
    'work'                  => 'Тег: робота',
    'weaving'               => 'Тег: плетіння',
    'bracelets'             => 'Тег: браслети',
    'ecology'               => 'Тег: екологія',
    'fundraising'           => 'Тег: збори',
    'animals'               => 'Тег: тварини',
    'help'                  => 'Тег: допомога',
    'with_children'         => 'Тег: з дітьми',
    'page403'               => 'Access Denied',
    'programs'              => 'Волонтерство',
    'needs_add'             => 'Додавання потреб',
    'needs_edit'            => 'Редагування потреб',
    'needs_details'         => 'Деталі потреб',
    'programs_add'          => 'Додавання програми',
    'programs_del'          => 'Видалення програми',
    'programs_edit'         => 'Редагування програми',
    'programs_details'      => 'Деталі програми',
    'admin_page'            => 'Сторінка адміністратора',
    'handler_add_needs'     => 'Обробка додавання потреб',
    'handler_del_needs'     => 'Обробка видалення потреб',
    'handler_edit_needs'    => 'Обробка редагування потреб',
    'handler_add_programs'  => 'Обробка додавання програми',
    'handler_del_programs'  => 'Обробка видалення програми',
    'handler_edit_programs' => 'Обробка редагування програми',
    'handler_del_users'     => 'Обробка видалення користувачів',
    'handler_edit1_users'   => 'Обробка редагування користувача',
    'handler_edit2_users'   => 'Обробка редагування користувача',
];